trigger:
  - master

pool:
  vmImage: 'windows-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '8.16.0'

  - script: npm install
  - script: npm run web:build
  - script: cd web && npm install && npm run dist

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/web/dist'
