export const FIND_CONNECTED_PRINTERS = "FIND_CONNECTED_PRINTERS"
export type FIND_CONNECTED_PRINTERS = typeof FIND_CONNECTED_PRINTERS

export const FIND_CONNECTED_PRINTERS_FULFILLED = "FIND_CONNECTED_PRINTERS_FULFILLED"
export type FIND_CONNECTED_PRINTERS_FULFILLED = typeof FIND_CONNECTED_PRINTERS_FULFILLED

export const FIND_CONNECTED_PRINTERS_REJECTED = "FIND_CONNECTED_PRINTERS_REJECTED"
export type FIND_CONNECTED_PRINTERS_REJECTED = typeof FIND_CONNECTED_PRINTERS_REJECTED

export const SELECT_PRINTER = "SELECT_PRINTER"
export type SELECT_PRINTER = typeof SELECT_PRINTER

export const UPDATE_TICKET = "UPDATE_TICKET"
export type UPDATE_TICKET = typeof UPDATE_TICKET

export const TICKET_PRINTED = "TICKET_PRINTED"
export type TICKET_PRINTED = typeof TICKET_PRINTED

export const SET_PRINTER_ENABLED = "SET_PRINTER_ENABLED"
export type SET_PRINTER_ENABLED = typeof SET_PRINTER_ENABLED

export const CLEAR_PRINTER_DEBUG_OUTPUT = "CLEAR_PRINTER_DEBUG_OUTPUT"
export type CLEAR_PRINTER_DEBUG_OUTPUT = typeof CLEAR_PRINTER_DEBUG_OUTPUT

export const APPEND_PRINTER_DEBUG_OUTPUT = "APPEND_PRINTER_DEBUG_OUTPUT"
export type APPEND_PRINTER_DEBUG_OUTPUT = typeof APPEND_PRINTER_DEBUG_OUTPUT

export const TOGGLE_DEBUG_OUTPUT = "TOGGLE_DEBUG_OUTPUT"
export type TOGGLE_DEBUG_OUTPUT = typeof TOGGLE_DEBUG_OUTPUT

export const SET_DEBUG_OUTPUT = "SET_DEBUG_OUTPUT"
export type SET_DEBUG_OUTPUT = typeof SET_DEBUG_OUTPUT

export const DISPLAY_PRINTER_NOTIFICATION = "DISPLAY_PRINTER_NOTIFICATION"
export type DISPLAY_PRINTER_NOTIFICATION = typeof DISPLAY_PRINTER_NOTIFICATION

export const HIDE_PRINTER_NOTIFICATION = "HIDE_PRINTER_NOTIFICATION"
export type HIDE_PRINTER_NOTIFICATION = typeof HIDE_PRINTER_NOTIFICATION
