export const SET_KIOSK_ID = "SET_KIOSK_ID"
export type SET_KIOSK_ID = typeof SET_KIOSK_ID

export const SET_KIOSK_SERIAL = "SET_KIOSK_SERIAL"
export type SET_KIOSK_SERIAL = typeof SET_KIOSK_SERIAL

export const SET_KIOSK_URL = "SET_KIOSK_URL"
export type SET_KIOSK_URL = typeof SET_KIOSK_URL

export const GET_KIOSK_ID_AND_DOMAIN_FROM_URL = "GET_KIOSK_ID_AND_DOMAIN_FROM_URL"
export type GET_KIOSK_ID_AND_DOMAIN_FROM_URL = typeof GET_KIOSK_ID_AND_DOMAIN_FROM_URL
