export const SET_PRINTER_CALLBACK = "SET_PRINTER_CALLBACK"
export type SET_PRINTER_CALLBACK = typeof SET_PRINTER_CALLBACK

export const PRINT_TICKET = "PRINT_TICKET"
export type PRINT_TICKET = typeof PRINT_TICKET

export const PRINT_TICKET_FULFILLED = "PRINT_TICKET_FULFILLED"
export type PRINT_TICKET_FULFILLED = typeof PRINT_TICKET_FULFILLED

export const PRINT_TICKET_REJECTED = "PRINT_TICKET_REJECTED"
export type PRINT_TICKET_REJECTED = typeof PRINT_TICKET_REJECTED
