/**
 * Ignore some expected warnings
 * see: https://jestjs.io/docs/en/tutorial-react.html#snapshot-testing-with-mocks-enzyme-and-react-16
 * see https://github.com/Root-App/react-native-mock-render/issues/6
 */
const originalConsoleError = console.error;
console.error = (message) => {
  if (message.startsWith('Warning:')) {
    return;
  }

  originalConsoleError(message);
};

jest.mock('react-native-device-info', () => ({
  getDeviceName: () => "test",
  getReadableVersion: () => "1.0.1",
  getUniqueID: () => "1234567890",
  getBrand: () => "Apple",
  getModel: () => "12inch",
  getDeviceId: () => "1",
  getAPILevel: () => "21",
  getSystemVersion: () => "9.0.0",
}))

jest.mock('@dnlowman/react-native-star-prnt', () => ({
  StarPRNT: {
    portDiscovery: jest.fn(),
    AlignmentPosition: {
      Center: "Center"
    },
    CutPaperAction: {
      PartialCutWithFeed: ""
    },
    print: jest.fn()
  }
}))

jest.mock('react-navigation', () => ({
    createStackNavigator: () => ({}),
    createDrawerNavigator: () => ({}),
    createSwitchNavigator: jest.fn(),
    withNavigation: (component) => { return component },
    NavigationActions: {
      back: () => ({ type: "NavigationAction/BACK" }),
      navigate: config => ({
        type: "NavigationAction/NAVIGATE",
        ...config
      }),
    },
    NavigationEvents: () => null
}))

jest.mock("../assets/images/logo-qudini.png", () => ({ uri: "logo-qudini.png" }))

jest.mock("../assets/images/printer.png", () => ({ uri: "printer.png" }))

jest.mock("rn-fetch-blob", () => ({
  fs: {
    dirs: {
      DocumentDir: ""
    }
  },
  config: () => ({
    fetch: (type, logoUrl) => ({
      path: () => () => ''
    })
  })
}))

jest.mock("../src/utils/flags", () => ({
  ad: { uri: "https://qa.qudini.com/static/ad.png" },
  ae: { uri: "https://qa.qudini.com/static/ae.png" },
  af: { uri: "https://qa.qudini.com/static/af.png" },
  ag: { uri: "https://qa.qudini.com/static/ag.png" },
  ai: { uri: "https://qa.qudini.com/static/ai.png" },
  al: { uri: "https://qa.qudini.com/static/al.png" },
  am: { uri: "https://qa.qudini.com/static/am.png" },
  ao: { uri: "https://qa.qudini.com/static/ao.png" },
  aq: { uri: "https://qa.qudini.com/static/aq.png" },
  ar: { uri: "https://qa.qudini.com/static/ar.png" },
  as: { uri: "https://qa.qudini.com/static/as.png" },
  at: { uri: "https://qa.qudini.com/static/at.png" },
  au: { uri: "https://qa.qudini.com/static/au.png" },
  aw: { uri: "https://qa.qudini.com/static/aw.png" },
  ax: { uri: "https://qa.qudini.com/static/ax.png" },
  az: { uri: "https://qa.qudini.com/static/az.png" },
  ba: { uri: "https://qa.qudini.com/static/ba.png" },
  bb: { uri: "https://qa.qudini.com/static/bb.png" },
  bd: { uri: "https://qa.qudini.com/static/bd.png" },
  be: { uri: "https://qa.qudini.com/static/be.png" },
  bf: { uri: "https://qa.qudini.com/static/bf.png" },
  bg: { uri: "https://qa.qudini.com/static/bg.png" },
  bh: { uri: "https://qa.qudini.com/static/bh.png" },
  bi: { uri: "https://qa.qudini.com/static/bi.png" },
  bj: { uri: "https://qa.qudini.com/static/bj.png" },
  bl: { uri: "https://qa.qudini.com/static/bl.png" },
  bm: { uri: "https://qa.qudini.com/static/bm.png" },
  bn: { uri: "https://qa.qudini.com/static/bn.png" },
  bo: { uri: "https://qa.qudini.com/static/bo.png" },
  bq: { uri: "https://qa.qudini.com/static/bq.png" },
  br: { uri: "https://qa.qudini.com/static/br.png" },
  bs: { uri: "https://qa.qudini.com/static/bs.png" },
  bt: { uri: "https://qa.qudini.com/static/bt.png" },
  bv: { uri: "https://qa.qudini.com/static/bv.png" },
  bw: { uri: "https://qa.qudini.com/static/bw.png" },
  by: { uri: "https://qa.qudini.com/static/by.png" },
  bz: { uri: "https://qa.qudini.com/static/bz.png" },
  ca: { uri: "https://qa.qudini.com/static/ca.png" },
  cc: { uri: "https://qa.qudini.com/static/cc.png" },
  cd: { uri: "https://qa.qudini.com/static/cd.png" },
  cf: { uri: "https://qa.qudini.com/static/cf.png" },
  cg: { uri: "https://qa.qudini.com/static/cg.png" },
  ch: { uri: "https://qa.qudini.com/static/ch.png" },
  ci: { uri: "https://qa.qudini.com/static/ci.png" },
  ck: { uri: "https://qa.qudini.com/static/ck.png" },
  cl: { uri: "https://qa.qudini.com/static/cl.png" },
  cm: { uri: "https://qa.qudini.com/static/cm.png" },
  cn: { uri: "https://qa.qudini.com/static/cn.png" },
  co: { uri: "https://qa.qudini.com/static/co.png" },
  cr: { uri: "https://qa.qudini.com/static/cr.png" },
  cu: { uri: "https://qa.qudini.com/static/cu.png" },
  cv: { uri: "https://qa.qudini.com/static/cv.png" },
  cw: { uri: "https://qa.qudini.com/static/cw.png" },
  cx: { uri: "https://qa.qudini.com/static/cx.png" },
  cy: { uri: "https://qa.qudini.com/static/cy.png" },
  cz: { uri: "https://qa.qudini.com/static/cz.png" },
  de: { uri: "https://qa.qudini.com/static/de.png" },
  dj: { uri: "https://qa.qudini.com/static/dj.png" },
  dk: { uri: "https://qa.qudini.com/static/dk.png" },
  dm: { uri: "https://qa.qudini.com/static/dm.png" },
  do: { uri: "https://qa.qudini.com/static/do.png" },
  dz: { uri: "https://qa.qudini.com/static/dz.png" },
  ec: { uri: "https://qa.qudini.com/static/ec.png" },
  ee: { uri: "https://qa.qudini.com/static/ee.png" },
  eg: { uri: "https://qa.qudini.com/static/eg.png" },
  eh: { uri: "https://qa.qudini.com/static/eh.png" },
  er: { uri: "https://qa.qudini.com/static/er.png" },
  es: { uri: "https://qa.qudini.com/static/es.png" },
  et: { uri: "https://qa.qudini.com/static/et.png" },
  fi: { uri: "https://qa.qudini.com/static/fi.png" },
  fj: { uri: "https://qa.qudini.com/static/fj.png" },
  fk: { uri: "https://qa.qudini.com/static/fk.png" },
  fm: { uri: "https://qa.qudini.com/static/fm.png" },
  fo: { uri: "https://qa.qudini.com/static/fo.png" },
  fr: { uri: "https://qa.qudini.com/static/fr.png" },
  ga: { uri: "https://qa.qudini.com/static/ga.png" },
  gb: { uri: "https://qa.qudini.com/static/gb.png" },
  gd: { uri: "https://qa.qudini.com/static/gd.png" },
  ge: { uri: "https://qa.qudini.com/static/ge.png" },
  gf: { uri: "https://qa.qudini.com/static/gf.png" },
  gg: { uri: "https://qa.qudini.com/static/gg.png" },
  gh: { uri: "https://qa.qudini.com/static/gh.png" },
  gi: { uri: "https://qa.qudini.com/static/gi.png" },
  gl: { uri: "https://qa.qudini.com/static/gl.png" },
  gm: { uri: "https://qa.qudini.com/static/gm.png" },
  gn: { uri: "https://qa.qudini.com/static/gn.png" },
  gp: { uri: "https://qa.qudini.com/static/gp.png" },
  gq: { uri: "https://qa.qudini.com/static/gq.png" },
  gr: { uri: "https://qa.qudini.com/static/gr.png" },
  gs: { uri: "https://qa.qudini.com/static/gs.png" },
  gt: { uri: "https://qa.qudini.com/static/gt.png" },
  gu: { uri: "https://qa.qudini.com/static/gu.png" },
  gw: { uri: "https://qa.qudini.com/static/gw.png" },
  gy: { uri: "https://qa.qudini.com/static/gy.png" },
  hk: { uri: "https://qa.qudini.com/static/hk.png" },
  hm: { uri: "https://qa.qudini.com/static/hm.png" },
  hn: { uri: "https://qa.qudini.com/static/hn.png" },
  hr: { uri: "https://qa.qudini.com/static/hr.png" },
  ht: { uri: "https://qa.qudini.com/static/ht.png" },
  hu: { uri: "https://qa.qudini.com/static/hu.png" },
  id: { uri: "https://qa.qudini.com/static/id.png" },
  ie: { uri: "https://qa.qudini.com/static/ie.png" },
  il: { uri: "https://qa.qudini.com/static/il.png" },
  im: { uri: "https://qa.qudini.com/static/im.png" },
  in: { uri: "https://qa.qudini.com/static/in.png" },
  io: { uri: "https://qa.qudini.com/static/io.png" },
  iq: { uri: "https://qa.qudini.com/static/iq.png" },
  ir: { uri: "https://qa.qudini.com/static/ir.png" },
  is: { uri: "https://qa.qudini.com/static/is.png" },
  it: { uri: "https://qa.qudini.com/static/it.png" },
  je: { uri: "https://qa.qudini.com/static/je.png" },
  jm: { uri: "https://qa.qudini.com/static/jm.png" },
  jo: { uri: "https://qa.qudini.com/static/jo.png" },
  jp: { uri: "https://qa.qudini.com/static/jp.png" },
  ke: { uri: "https://qa.qudini.com/static/ke.png" },
  kg: { uri: "https://qa.qudini.com/static/kg.png" },
  kh: { uri: "https://qa.qudini.com/static/kh.png" },
  ki: { uri: "https://qa.qudini.com/static/ki.png" },
  km: { uri: "https://qa.qudini.com/static/km.png" },
  kn: { uri: "https://qa.qudini.com/static/kn.png" },
  kp: { uri: "https://qa.qudini.com/static/kp.png" },
  kr: { uri: "https://qa.qudini.com/static/kr.png" },
  kw: { uri: "https://qa.qudini.com/static/kw.png" },
  ky: { uri: "https://qa.qudini.com/static/ky.png" },
  kz: { uri: "https://qa.qudini.com/static/kz.png" },
  la: { uri: "https://qa.qudini.com/static/la.png" },
  lb: { uri: "https://qa.qudini.com/static/lb.png" },
  lc: { uri: "https://qa.qudini.com/static/lc.png" },
  li: { uri: "https://qa.qudini.com/static/li.png" },
  lk: { uri: "https://qa.qudini.com/static/lk.png" },
  lr: { uri: "https://qa.qudini.com/static/lr.png" },
  ls: { uri: "https://qa.qudini.com/static/ls.png" },
  lt: { uri: "https://qa.qudini.com/static/lt.png" },
  lu: { uri: "https://qa.qudini.com/static/lu.png" },
  lv: { uri: "https://qa.qudini.com/static/lv.png" },
  ly: { uri: "https://qa.qudini.com/static/ly.png" },
  ma: { uri: "https://qa.qudini.com/static/ma.png" },
  mc: { uri: "https://qa.qudini.com/static/mc.png" },
  md: { uri: "https://qa.qudini.com/static/md.png" },
  me: { uri: "https://qa.qudini.com/static/me.png" },
  mf: { uri: "https://qa.qudini.com/static/mf.png" },
  mg: { uri: "https://qa.qudini.com/static/mg.png" },
  mh: { uri: "https://qa.qudini.com/static/mh.png" },
  mk: { uri: "https://qa.qudini.com/static/mk.png" },
  ml: { uri: "https://qa.qudini.com/static/ml.png" },
  mm: { uri: "https://qa.qudini.com/static/mm.png" },
  mn: { uri: "https://qa.qudini.com/static/mn.png" },
  mo: { uri: "https://qa.qudini.com/static/mo.png" },
  mp: { uri: "https://qa.qudini.com/static/mp.png" },
  mq: { uri: "https://qa.qudini.com/static/mq.png" },
  mr: { uri: "https://qa.qudini.com/static/mr.png" },
  ms: { uri: "https://qa.qudini.com/static/ms.png" },
  mt: { uri: "https://qa.qudini.com/static/mt.png" },
  mu: { uri: "https://qa.qudini.com/static/mu.png" },
  mv: { uri: "https://qa.qudini.com/static/mv.png" },
  mw: { uri: "https://qa.qudini.com/static/mw.png" },
  mx: { uri: "https://qa.qudini.com/static/mx.png" },
  my: { uri: "https://qa.qudini.com/static/my.png" },
  mz: { uri: "https://qa.qudini.com/static/mz.png" },
  na: { uri: "https://qa.qudini.com/static/na.png" },
  nc: { uri: "https://qa.qudini.com/static/nc.png" },
  ne: { uri: "https://qa.qudini.com/static/ne.png" },
  nf: { uri: "https://qa.qudini.com/static/nf.png" },
  ng: { uri: "https://qa.qudini.com/static/ng.png" },
  ni: { uri: "https://qa.qudini.com/static/ni.png" },
  nl: { uri: "https://qa.qudini.com/static/nl.png" },
  no: { uri: "https://qa.qudini.com/static/no.png" },
  np: { uri: "https://qa.qudini.com/static/np.png" },
  nr: { uri: "https://qa.qudini.com/static/nr.png" },
  nu: { uri: "https://qa.qudini.com/static/nu.png" },
  nz: { uri: "https://qa.qudini.com/static/nz.png" },
  om: { uri: "https://qa.qudini.com/static/om.png" },
  pa: { uri: "https://qa.qudini.com/static/pa.png" },
  pe: { uri: "https://qa.qudini.com/static/pe.png" },
  pf: { uri: "https://qa.qudini.com/static/pf.png" },
  pg: { uri: "https://qa.qudini.com/static/pg.png" },
  ph: { uri: "https://qa.qudini.com/static/ph.png" },
  pk: { uri: "https://qa.qudini.com/static/pk.png" },
  pl: { uri: "https://qa.qudini.com/static/pl.png" },
  pm: { uri: "https://qa.qudini.com/static/pm.png" },
  pn: { uri: "https://qa.qudini.com/static/pn.png" },
  pr: { uri: "https://qa.qudini.com/static/pr.png" },
  ps: { uri: "https://qa.qudini.com/static/ps.png" },
  pt: { uri: "https://qa.qudini.com/static/pt.png" },
  pw: { uri: "https://qa.qudini.com/static/pw.png" },
  py: { uri: "https://qa.qudini.com/static/py.png" },
  qa: { uri: "https://qa.qudini.com/static/qa.png" },
  re: { uri: "https://qa.qudini.com/static/re.png" },
  ro: { uri: "https://qa.qudini.com/static/ro.png" },
  rs: { uri: "https://qa.qudini.com/static/rs.png" },
  ru: { uri: "https://qa.qudini.com/static/ru.png" },
  rw: { uri: "https://qa.qudini.com/static/rw.png" },
  sa: { uri: "https://qa.qudini.com/static/sa.png" },
  sb: { uri: "https://qa.qudini.com/static/sb.png" },
  sc: { uri: "https://qa.qudini.com/static/sc.png" },
  sd: { uri: "https://qa.qudini.com/static/sd.png" },
  se: { uri: "https://qa.qudini.com/static/se.png" },
  sg: { uri: "https://qa.qudini.com/static/sg.png" },
  sh: { uri: "https://qa.qudini.com/static/sh.png" },
  si: { uri: "https://qa.qudini.com/static/si.png" },
  sj: { uri: "https://qa.qudini.com/static/sj.png" },
  sk: { uri: "https://qa.qudini.com/static/sk.png" },
  sl: { uri: "https://qa.qudini.com/static/sl.png" },
  sm: { uri: "https://qa.qudini.com/static/sm.png" },
  sn: { uri: "https://qa.qudini.com/static/sn.png" },
  so: { uri: "https://qa.qudini.com/static/so.png" },
  sr: { uri: "https://qa.qudini.com/static/sr.png" },
  ss: { uri: "https://qa.qudini.com/static/ss.png" },
  st: { uri: "https://qa.qudini.com/static/st.png" },
  sv: { uri: "https://qa.qudini.com/static/sv.png" },
  sx: { uri: "https://qa.qudini.com/static/sx.png" },
  sy: { uri: "https://qa.qudini.com/static/sy.png" },
  sz: { uri: "https://qa.qudini.com/static/sz.png" },
  tc: { uri: "https://qa.qudini.com/static/tc.png" },
  td: { uri: "https://qa.qudini.com/static/td.png" },
  tf: { uri: "https://qa.qudini.com/static/tf.png" },
  tg: { uri: "https://qa.qudini.com/static/tg.png" },
  th: { uri: "https://qa.qudini.com/static/th.png" },
  tj: { uri: "https://qa.qudini.com/static/tj.png" },
  tk: { uri: "https://qa.qudini.com/static/tk.png" },
  tl: { uri: "https://qa.qudini.com/static/tl.png" },
  tm: { uri: "https://qa.qudini.com/static/tm.png" },
  tn: { uri: "https://qa.qudini.com/static/tn.png" },
  to: { uri: "https://qa.qudini.com/static/to.png" },
  tr: { uri: "https://qa.qudini.com/static/tr.png" },
  tt: { uri: "https://qa.qudini.com/static/tt.png" },
  tv: { uri: "https://qa.qudini.com/static/tv.png" },
  tw: { uri: "https://qa.qudini.com/static/tw.png" },
  tz: { uri: "https://qa.qudini.com/static/tz.png" },
  ua: { uri: "https://qa.qudini.com/static/ua.png" },
  ug: { uri: "https://qa.qudini.com/static/ug.png" },
  um: { uri: "https://qa.qudini.com/static/um.png" },
  us: { uri: "https://qa.qudini.com/static/us.png" },
  uy: { uri: "https://qa.qudini.com/static/uy.png" },
  uz: { uri: "https://qa.qudini.com/static/uz.png" },
  va: { uri: "https://qa.qudini.com/static/va.png" },
  vc: { uri: "https://qa.qudini.com/static/vc.png" },
  ve: { uri: "https://qa.qudini.com/static/ve.png" },
  vg: { uri: "https://qa.qudini.com/static/vg.png" },
  vi: { uri: "https://qa.qudini.com/static/vi.png" },
  vn: { uri: "https://qa.qudini.com/static/vn.png" },
  vu: { uri: "https://qa.qudini.com/static/vu.png" },
  wf: { uri: "https://qa.qudini.com/static/wf.png" },
  ws: { uri: "https://qa.qudini.com/static/ws.png" },
  ye: { uri: "https://qa.qudini.com/static/ye.png" },
  yt: { uri: "https://qa.qudini.com/static/yt.png" },
  za: { uri: "https://qa.qudini.com/static/za.png" },
  zm: { uri: "https://qa.qudini.com/static/zm.png" },
  zw: { uri: "https://qa.qudini.com/static/zw.png" },
  zz: { uri: "https://qa.qudini.com/static/zz.png" },
}))
