# This is a basic workflow to help you get started with Actions

name: Tizen Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ tizen-project-structure ]
  pull_request:
    branches: [ tizen-project-structure ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build Tizen app
        id: tizen-build-action
        uses: sourcetoad/tizen-build-action@v1.0.1
        with:
          project-dir: ${{ github.workspace }}/tizen
          author-key: ${{ secrets.TIZEN_AUTHOR_KEY }}
          author-password: ${{ secrets.TIZEN_AUTHOR_KEY_PW }}

      - name: Upload Tizen package artifact
        uses: actions/upload-artifact@v2
        with:
           name: app-${{ github.sha }}.wgt
           path: ${{ steps.tizen-build-action.outputs.package-artifact }}
